import { execFileSync } from 'node:child_process';
import type { PhaseResult } from '../types.js';

/**
 * Generate a markdown PR body from agent run metadata.
 */
export function generatePrBody(options: {
  title: string;
  description: string;
  diffStat: string;
  phases: PhaseResult[];
  totalCost: number;
  testResult?: { passed: boolean; output: string };
  codeReviewSummary?: string;
}): string {
  const { description, diffStat, phases, totalCost, testResult, codeReviewSummary } = options;

  const sections: string[] = [];

  // Summary
  sections.push(`## Summary\n${description}`);

  // Changes
  sections.push(`## Changes\n\`\`\`\n${diffStat}\n\`\`\``);

  // Test Results
  let testSection: string;
  if (!testResult) {
    testSection = '## Test Results\n⚠️ Tests skipped';
  } else if (testResult.passed) {
    testSection = '## Test Results\n✅ All tests passed';
  } else {
    const truncated = testResult.output.split('\n').slice(-30).join('\n');
    testSection = `## Test Results\n❌ Tests failing\n\`\`\`\n${truncated}\n\`\`\``;
  }
  sections.push(testSection);

  // Code Review Summary (optional)
  if (codeReviewSummary) {
    sections.push(`## Code Review\n${codeReviewSummary}`);
  }

  // Agent Metadata
  const phaseList = phases
    .map((p) => `  - ${p.success ? '✅' : '❌'} ${p.phase} ($${p.costUsd.toFixed(4)}, ${(p.durationMs / 1000).toFixed(1)}s)`)
    .join('\n');

  sections.push(`## Agent Metadata\n- Total cost: $${totalCost.toFixed(4)}\n- Phases:\n${phaseList}`);

  // Footer
  sections.push('---\n*Generated by coding-agent*');

  return sections.join('\n\n');
}

/**
 * Create a pull request using the `gh` CLI.
 * Returns the PR URL on success, or null if `gh` is not available or the command fails.
 */
export function createPr(
  cwd: string,
  branchName: string,
  title: string,
  body: string,
  isDraft: boolean,
): Promise<string | null> {
  return new Promise((resolve) => {
    try {
      const args = ['pr', 'create', '--title', title, '--body', body, '--head', branchName];
      if (isDraft) {
        args.push('--draft');
      }

      const stdout = execFileSync('gh', args, {
        cwd,
        encoding: 'utf-8',
        stdio: ['pipe', 'pipe', 'pipe'],
        timeout: 60_000,
      }).trim();

      resolve(stdout || null);
    } catch {
      resolve(null);
    }
  });
}
