import { execFileSync } from 'node:child_process';
import type { StageResult } from '../types.js';

export function generatePrBody(options: {
  title: string;
  description: string;
  diffStat: string;
  stages: StageResult[];
  totalCost: number;
}): string {
  const { description, diffStat, stages, totalCost } = options;

  const sections: string[] = [];

  sections.push(`## Summary\n${description}`);

  sections.push(`## Changes\n\`\`\`\n${diffStat}\n\`\`\``);

  const stageList = stages
    .map((s) => `  - ${s.success ? 'ok' : 'err'} ${s.stage} ($${s.costUsd.toFixed(4)}, ${(s.durationMs / 1000).toFixed(1)}s)`)
    .join('\n');

  sections.push(`## Agent Metadata\n- Total cost: $${totalCost.toFixed(4)}\n- Stages:\n${stageList}`);

  sections.push('---\n*Generated by coding-agent v2*');

  return sections.join('\n\n');
}

export function createPr(
  cwd: string,
  branchName: string,
  title: string,
  body: string,
  isDraft: boolean,
): Promise<string | null> {
  return new Promise((resolve) => {
    try {
      const args = ['pr', 'create', '--title', title, '--body', body, '--head', branchName];
      if (isDraft) {
        args.push('--draft');
      }

      const stdout = execFileSync('gh', args, {
        cwd,
        encoding: 'utf-8',
        stdio: ['pipe', 'pipe', 'pipe'],
        timeout: 60_000,
      }).trim();

      resolve(stdout || null);
    } catch {
      resolve(null);
    }
  });
}
